{
    "error": "An error occurred: HTTPSConnectionPool(host='thunderscans.com', port=443): Max retries exceeded with url: /manga/the-strongest-chef-in-another-world/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000176A9753740>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
}