{
    "error": "An error occurred: HTTPSConnectionPool(host='thunderscans.com', port=443): Max retries exceeded with url: /manga/5597283480-unparalleled-in-the-online-gaming-world (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000176A99119A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))"
}